### PR TITLE
Adjust conflicts in `2.9.x` -> `3.0.x` merge-up

### PR DESCRIPTION
**Pull request by tobias-trozowski**
Fixed conflicts in merge-up

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
LGTM, thanks @tobias-trozowski!

**Comment by Ocramius** [comment]
Hmm, 7.3 builds failed 🤔

**Comment by tobias-trozowski** [comment]
i might have used the wrong container for updating the lock file after merge... :O

**Comment by tobias-trozowski** [comment]
@Ocramius cant reproduce the error with phpcs locally, any idea?

**Comment by Ocramius** [comment]
Perhaps we can attempt removing `TestAsset` exclusions?

```
Warning: No PHP code was found in this file and short open tags are not allowed by this install of PHP. This file may be using short open tags but PHP does not allow them.
```

I don't know where this may be coming from either: the `-q` flag makes it annoyingly hard to figure it out :|

**Comment by tobias-trozowski** [comment]
any chance to alter the workflow command without changing `laminas/laminas-ci-matrix-action`?

**Comment by Ocramius** [comment]
I'd rather suggest running the action docker container locally

**Comment by tobias-trozowski** [comment]
Found it... 
```
Running ./vendor/bin/phpcs
.............................................W.......

FILE: /github/workspace/test/Adapter/DbTableTest.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | WARNING | No PHP code was found in this file and short open tags
   |         | are not allowed by this install of PHP. This file may
   |         | be using short open tags but PHP does not allow them.
----------------------------------------------------------------------
```

**Comment by tobias-trozowski** [comment]
is it possible to merge this and PR and #27 or are they waiting for anything?

**Comment by Ocramius** [comment]
@tobias-trozowski mostly oversight - didn't receive further notifications about it, hence it was ignored :)

**Review by Ocramius — APPROVED** [review]
Thanks @tobias-trozowski!

**Pull request merged**
