### PR TITLE
Update minimum PHP version to 7.4, update `phpunit/phpunit` to `^9.3.4` and `laminas/laminas-coding-standard` to `~2.4.0`

### PR DESCRIPTION
**Pull request by internalsystemerror**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

This PR:
- Updates the minimum supported PHP version to 7.4
- Updates `phpunit/phpunit` to `^9.3.4` as the XSD is required for CI (see https://github.com/laminas/laminas-authentication/runs/8287606784?check_suite_focus=true)
- Updates all dependencies to the minimum installed versions on PHP 7.4
- Updates `laminas/laminas-coding-standard` to `~2.4.0` (closes https://github.com/laminas/laminas-authentication/pull/40 and allows https://github.com/laminas/laminas-authentication/pull/39 to proceed once regenerated)

### CODE REVIEW

**Comment by internalsystemerror** [comment]
I'm not sure what milestone to attach to. I checked out 2.11.x thinking that was the future minor. This should technically be part of 2.12.x. How does that work with `automatic-releases`?

**Review by gsteel — APPROVED** [review]
LGTM 👍

**Comment by gsteel** [comment]
2.12.x should be fine right - Automatic releases will just create a merge-up for 3.0.x

**Comment by internalsystemerror** [comment]
There currently is no `2.12.x` branch. But if I merge this and add it to the 2.12.0 milestone, then there will be changes on the `2.11.x` branch without a `2.11.1` release. I wonder if could just create the branch manually?

**Comment by internalsystemerror** [comment]
Branch created, through the UI too, was easy enough.

**Comment by Ocramius** [comment]
Related: https://github.com/laminas/automatic-releases/issues/209

**Pull request merged**
