### PR TITLE
Upgrade laminas-coding-standard to 2.3

### PR DESCRIPTION
**Pull request by arueckauer**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

This PR updates the `laminas-coding-standard` to version `2.3.0` and provides necessary code changes.

### CODE REVIEW

**Comment by Ocramius** [comment]
@froschdesign beware: you adjusted milestone to `2.9.0`, but the target branch states `3.0.x`

**Comment by froschdesign** [comment]
@Ocramius 
Right, the target branch is wrong. But there is no 2.9.0 branch and that doesn't mean we need a major version to update the coding standard.

**Comment by arueckauer** [comment]
How would you like to proceed? Create a `2.9.x` branch and I rebase to it?

**Comment by arueckauer** [comment]
@Ocramius & @froschdesign It looks like the tests are missing some env configuration (?). How can that be solved?

**Comment by arueckauer** [comment]
@froschdesign / @Ocramius Originally this was branched off of the default branch `3.0.x`. Should I rebase to `2.9.x`?

**Comment by froschdesign** [comment]
@arueckauer 
> Should I rebase to `2.9.x`?

Yes, please! (some more cherry-pick is needed)

**Comment by Ocramius** [comment]
I think the `2.9.x` and `3.0.x` now already have some half-phpcs setup - needs some checking (and potentially rebasing or closing, depending on outcome)

**Pull request closed without merging**
