### PR TITLE
PHP 8.1 support

### LINKED ISSUE #23: PHP 8.1 support
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

PHP with [version 8.1 is released](https://www.php.net/releases/8.1/index.php) and for this component the support of the new version is still missing.

### PR DESCRIPTION
**Pull request by tobias-trozowski**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description
Based on https://github.com/laminas/laminas-authentication/pull/24

- added tests to cover fixed behaviour of sqlite data-types ([#38334](https://bugs.php.net/bug.php?id=38334))
- bumped laminas/laminas-db to ^2.13
- bumped laminas/laminas-ldap to ^2.12
- bumped laminas/laminas-http to ^2.15
- bumped laminas/laminas-session to ^2.12

query results of sqlite have changed in php 8.1, see https://bugs.php.net/bug.php?id=38334
`Fixed bug #38334 (Proper data-type support for PDO_SQLITE).` (https://www.php.net/ChangeLog-8.php)

Fixes #24 
Fixes #23

### CODE REVIEW

**Comment by Koen1999** [comment]
I think this solution could be appropriate if tests pass.

**Comment by Koen1999** [comment]
On the other hand, it also avoids the problem by adjusting the test. Users of this function may still experience bugs due to the changed type.

**Review by Koen1999 — APPROVED** [review]

**Comment by Ocramius** [comment]
> Users of this function may still experience bugs due to the changed type.

Not fixable on this end: that requires a better DB abstraction then :-\

**Review by Ocramius — APPROVED** [review]
Thanks @tobias-trozowski and @Koen1999! :ship:

**Comment by Koen1999** [comment]
I would also like to thank @Ocramius, @snapshotpl and @froschdesign for enabling me to help adding PHP 8.1 support to several Laminas repositories :)

My study association has greatly benefited from the work you have done on Laminas, and your predecessors on Zend framework.

**Pull request merged**
